### ISSUE TITLE
Hotstrings and non-grabbing Hotkeys don't work in some applications

### ISSUE THREAD

**Issue by phil294** [phil294/AHK_X11#1]
such as in many (all?) Gtk-based apps. :-(

The exact same problem is described here: https://stackoverflow.com/a/22773051/3779853
See
> It's not reliable but most of the time it works [...] You may investigate why it does fail sometimes

the same code logic is present in ahk_x11, but I haven't been able to figure out the fix for it. Grabbing Hotkeys always work.

**Comment by phaleth** [comment]
So far the only place where I could see a hotstring work properly is the Brave Web Browser.

Once the hotstring is triggered in a place where it does not work the ahk script has to be reloaded.

![4hkj9k78gf8](https://user-images.githubusercontent.com/29838606/187653623-b726a0b2-ab57-42f6-af5f-3e5e6cf49e88.gif)

**Comment by phil294** [comment]
so apparently this is fixable by using [recordlib](https://www.x.org/releases/X11R7.7/doc/libXtst/recordlib.html) from libxtst, sample implementation from [espanso here](https://github.com/espanso/espanso/blob/dev/espanso-detect/src/x11/native.cpp).

As always with X11, it's a PITA. How people work with this stuff is beyond me, the docs and api are apparently not designed to be used by human beings, so I just can't be bothered right now. But eventually...

Luckily, espanso seems to have mastered Hotstring-like functionality perfectly on both X11 and Wayland (without sudo rights?!), so it seems we can borrow large chunks of code from there.

**Comment by phaleth** [comment]
> so apparently this is fixable by using [recordlib](https://www.x.org/releases/X11R7.7/doc/libXtst/recordlib.html) from libxtst, sample implementation from [espanso here](https://github.com/espanso/espanso/blob/dev/espanso-detect/src/x11/native.cpp).

Nice find. I stumbled upon the mention of espanso on the hacker news thread, today.

**Comment by phil294** [comment]
good news, it works perfectly with recordlib. Hopefully this is indeed installed on every common x11 system, but it looks like it.

I'll probably add `LButton`/`RButton` support next, and then make a new release in a few days to weeks.

**Comment by phaleth** [comment]
> good news, it works perfectly with recordlib ([1](https://github.com/phil294/AHK_X11/commit/adc7cacd1d81d4728da0b6db1bcb966976326eab), [2](https://github.com/TamasSzekeres/x11-cr/pull/18/files)). Hopefully this is indeed installed on every common x11 system, but it looks like it.

That's great news!

I'm on MATE desktop. Will see how hotkeys work after the release for sure.

**Comment by phil294** [comment]
It's released now: https://github.com/phil294/AHK_X11/releases/tag/0.2.0

Should you encounter any issues, feel free to post them here (or open up a new issue).

**Comment by phaleth** [comment]
It's flawless :tada: 

![z897io89l47j](https://user-images.githubusercontent.com/29838606/193448124-5b59e23c-9e48-4f47-b707-2c9628c774ef.gif)


Thank you!

I guess I should try writing an ahk script. Seems like the 0.2.0 version is capable enough for at least one use case I can think of right now. :smile:
