### ISSUE TITLE
My script doesn't work.. I use autohotkey format

### ISSUE THREAD

**Issue by kokqi** [phil294/AHK_X11#10]
![image](https://user-images.githubusercontent.com/78592988/190837136-30c619dd-dc65-47bc-9b7c-522c7107ee89.png)

**Comment by phil294** [comment]
From the Readme:
> most likely never full compatibility [...] Currently about 60% of work is done [...] many modern AHK features are missing, especially expressions (:=, % v), classes, objects and functions, so you probably can't just port your scripts from Windows [...]

For a list of commands, please see the [alphabetical list of commands on ahk_x11's documentation page](https://phil294.github.io/AHK_X11/#commands.htm). Your command `GetKeyState` exists but is marked as `TODO`, this means is hasn't been implemented yet. Contributions always welcome though.

**Comment by phil294** [comment]
FYI @kokqi `GetKeyState` has been added recently

**Comment by kokqi** [comment]
thx
