### ISSUE TITLE
[ARH bugs] ARH with asterisk option fails first time

### ISSUE THREAD

**Issue by Drugoy** [phil294/AHK_X11#12]
A hotstring is generally just a type of trigger for some code. The code block may be arbitrary. A subset of hotstrings is **a**uto-**r**eplacing **h**otstrings (**ARH**otstrings, **ARH**s), that's when all the hotstring does is just replaces the trigger's text with something else, like replacing `btw` with `by the way`.

Generally hotstrings require an ending character, but `*` option in AHK allowed to fire them right away (when the last character of the hotstring got typed), but in AHK_X11 I see it currently has a bug:

Script's code: `:*:btw::by the way`
Input: `btw{Space}btw`
Expected Result: `by the way by the way`
Actual Result: `btw by the way`
Extra Info: the problem doesn't occur if hotstring is defined without `*` option.
The workaround: add `return` above hotstring declaration.

**Comment by phil294** [comment]
Hi @Drugoy,
did you test this with the most recent version 0.2.0 (released yesterday)? Because the expected result `btw{Space}btw` -> `by the way by the way` is exactly what I'm seeing, reliably. Also,
>  The workaround: add return above hotstring declaration.

Any `Return`s anywhere around an ARH, below or above, must not and can not influence the hotstrings.

So could you please check this again?

**Comment by phil294** [comment]
regarding the first two paragraphs: Yes, that's the specification I hope to have adhered to. So at least the theory is correct here :)

**Comment by Drugoy** [comment]
Yes, I've seen the release, read the changelog and hence the ticket :)

**Comment by phil294** [comment]
ok, so what if your script is `:*:btw::by the way` and you type `btw btw btw btw btw btw`? which ones are being replaced?

**Comment by phil294** [comment]
... and does it change if you proceed the very first one with a space?

**Comment by Drugoy** [comment]
Seems like your guess was correct. I was testing in the terminal, so I thought ctrl+c reset the sequence. But it does not.
Tested via `echo a{Enter}btw` - it then immediately works out correctly.

**Comment by phil294** [comment]
on Windows, Hotstring matches are aborted on either of

- mouse click
- ctrl+key, probably also alt+key etc., I didn't check the official source
- window change

as it happens,

- abort-on-click is already implemented.
- I now added abort on any `ctrl, alt, altgr or super (win)` PLUS `some other key` combination. This will be part of the next release.
- window change detection is probably not worth the effort, as in 99% of cases you'd only change the window yourself by either clicking or alt+tabbing, which is now both detected as above. It would be possible to listen to focus change events with recordlib as well.
