### ISSUE TITLE
[ARH bugs] replacement's case depends on the state of shift modifier at the time of typing ending char

### ISSUE THREAD

**Issue by Drugoy** [phil294/AHK_X11#14]
Script's code: `::btw::by the way`
Input: `btw{ShiftDn}{Space}`
Expected Result: `by the way `.
Actual Result: `BY THE WAY `.

**Comment by phil294** [comment]
I fixed this now by unsetting modifiers around `send` behavior. However, if you manage to e.g. press `Shift` **while** the `by the way` typing takes place, this will still result in something along the lines of `by the wAY`. This gets especially interesting when you set a high `SetKeyDelay` (command is currently missing). Don't know how Windows AHK does it in this case.
