### ISSUE TITLE
!j:: Send {Down} | Doesn't work or am I doing something wrong?

### ISSUE THREAD

**Issue by navakelvin** [phil294/AHK_X11#15]
Old Windows user, Autohotkey lover looking for an alternative.

Just as I would on Windows i tried the following but without success.

```autohotkey
!j:: Send {Down}
; It's the only line I've written in the `*.ahk` file.
```
I also tried with `{DOWN}` in upper case. No way did I get it.

Am I doing this wrong by programming it like I would on Windows? How is it supposed to be done?

Thanks.

**Comment by phil294** [comment]
Hello,

no, your code is totally fine, but there's a bug in ahk_x11 where hotkeys + `Send` don't work together well. In your case, I think the ALT key is not released, but even without the `!`, it doesn't work. I hope to get around to fixing this within this week, so please check back later, or -

workaround:

```autohotkey
!j::
sleep 100
send {down}
return
```

**Comment by phil294** [comment]
should work now
