### ISSUE TITLE
Add support for mouse buttons in Send

### ISSUE THREAD

**Issue by SmartManoj** [phil294/AHK_X11#19]
`
AppsKey:: Send {RButton}`
Nothing happens when pressed for first time. And second time it's default action is performed.
OS version: manjaro-xfce-21.3.7-220816-linux515

**Comment by phil294** [comment]
mouse buttons are not yet supported inside key sequences, but soon may be. For now, you need to use `MouseClick` instead:

    AppsKey::MouseClick, R

which works fine for me.

**Comment by phil294** [comment]
this was fixed last week with version 0.5.0 https://github.com/phil294/AHK_X11/releases (9c145a668c0cdeb421c3be4429afd824628e0779)
