### ISSUE TITLE
Creating functions does not work

### ISSUE THREAD

**Issue by 19s-fautley-k** [phil294/AHK_X11#21]
Hi, trying to port a new script to work with this version. Got past the lack of #include, now stuck at function definition.
The code:
```
SendObsCmd(cmd) {
  FileAppend, %cmd%`n, %obsFile%
}
```
The error:
```
Syntax Error in line 9:
Command 'sendobscmd(cmd)' not found.

Line content was: 'SendObsCmd(cmd) {'.

The program will exit.
```

**Comment by phil294** [comment]
Hello,

functions are not implemented. Maybe some day, but they are not part of the 1.0.24 spec which I am trying to carry out currently. Expressions (`:=`, functions, ...) are quite a beast so personally I don't estimate to work on this in the foreseeable future.

This should also all be explained in the Readme - suggestions on how to improve it are always welcome though.

(Same thing with `#Include`)
