### ISSUE TITLE
nothing happens when I double click ahk_11

### ISSUE THREAD

**Issue by kokqi** [phil294/AHK_X11#23]

**Comment by phil294** [comment]
after downloading it, you mean? the installer?

can you run it in the terminal and see the potential error messages shown, please?

If you are running Arch Linux, your problem is probably also #18. If so, this will be fixed in just a few days.

**Comment by kokqi** [comment]
well im using ubuntu linux 
![image](https://user-images.githubusercontent.com/78592988/204298269-059334aa-250d-46bd-b884-d4a170eb47dc.png)

**Comment by kokqi** [comment]
> after downloading it, you mean? the installer?
> 
> can you run it in the terminal and see the potential error messages shown, please?
> 
> If you are running Arch Linux, your problem is probably also #18. If so, this will be fixed in just a few days.

yes, the installer

**Comment by phil294** [comment]
where did you get the AppImage from? where/how did you download it?

either way, seems to be the libssl  problem again, so will be fixed soon

**Comment by kokqi** [comment]
Just ignore it, I just rename it so

**Comment by phil294** [comment]
ok

**Comment by phil294** [comment]
closed with 9c0de54d
