### ISSUE TITLE
 compile error on debian bullseye

### ISSUE THREAD

**Issue by Jackfritt** [phil294/AHK_X11#31]
sudo apt-get install libxinerama-dev libxkbcommon-dev libxtst-dev libgtk-3-dev libxi-dev libx11-dev libgirepository1.0-dev libatspi2.0-dev libssl-dev

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libatspi2.0-dev is already the newest version (2.38.0-4).
libgirepository1.0-dev is already the newest version (1.66.1-1+b1).
libgtk-3-dev is already the newest version (3.24.24-4+deb11u2).
libx11-dev is already the newest version (2:1.7.2-1).
libxi-dev is already the newest version (2:1.7.10-1).
libxinerama-dev is already the newest version (2:1.1.4-2).
libxkbcommon-dev is already the newest version (1.0.3-2).
libxtst-dev is already the newest version (2:1.2.3-1).
libssl-dev is already the newest version (1.1.1n-0+deb11u3).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

LANG=C curl -fsSL https://crystal-lang.org/install.sh | LANG=C sudo bash
...
Fetched 17.5 kB in 1s (17.0 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gpg is already the newest version (2.2.27-2+deb11u2).
wget is already the newest version (1.21-1+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
deb http://download.opensuse.org/repositories/devel:languages:crystal/Debian_Unstable/ /
...
Get:10 http://download.opensuse.org/repositories/devel:languages:crystal/Debian_Unstable  InRelease [1557 B]
Get:20 http://download.opensuse.org/repositories/devel:languages:crystal/Debian_Unstable  Packages [4798 B]
Fetched 23.8 kB in 2s (11.2 kB/s)  
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
crystal is already the newest version (1.7.0-1+2.9).

shards install

Resolving dependencies
Fetching https://github.com/spider-gazelle/tasker.git
Fetching https://github.com/tamasszekeres/x11-cr.git
Fetching https://github.com/phil294/xtst-cr.git
Fetching https://github.com/phil294/x_do.cr.git
Fetching https://github.com/jhass/crystal-gobject.git
Fetching https://github.com/jhass/crystal-malloc_pthread_shim.git
Fetching https://github.com/kostya/cron_parser.git
Fetching https://github.com/crystal-community/future.cr.git
Shard "x11" version (1.0.0) doesn't match tag version (1.1.1)
Shard "x11" version (1.0.0) doesn't match tag version (1.1.1)
Installing cron_parser (0.4.0)
Installing future (1.0.0)
Installing tasker (2.0.7)
Installing x11 (1.1.1)
Installing xtst (1.0.0 at 202d2ae)
Installing x_do (0.8.3 at 94f755a)
Installing gobject (0.10.0)
Installing malloc_pthread_shim (0.1.0)
Postinstall of malloc_pthread_shim: make

 ./setup_dependencies.sh

building Gtk 3.0 namespace...
building xlib 2.0 namespace...
building GObject 2.0 namespace...
building GLib 2.0 namespace...
building Gio 2.0 namespace...
building GModule 2.0 namespace...
building Atk 1.0 namespace...
building freetype2 namespace...
building HarfBuzz 0.0 namespace...
building GdkPixbuf 2.0 namespace...
building cairo 1.0 namespace...
building Pango 1.0 namespace...
building Gdk 3.0 namespace...
building DBus 1.0 namespace...
building Atspi 2.0 namespace...
building GdkX11 3.0 namespace...
fix some dependency code...

shards build -Dpreview_mt

Dependencies are satisfied
Building: ahk_x11
Error target ahk_x11 failed to compile:
Showing last frame. Use --error-trace for full trace.

In src/cmd/x11/window/win-util.cr:18:54

 18 | win = XDo::Window.new(thread.runner.display.x_do.xdo_p, wid)
                                                       ^----
Error: private method 'xdo_p' called for XDo

Also tried this but same compile error

shards build -Dpreview_mt --link-flags="-no-pie -L$PWD/static -Wl,-Bstatic -lxdo -lxkbcommon -lXinerama -lXext -lXtst -lXi -levent_pthreads -levent -lpcre -Wl,-Bdynamic"

Dependencies are satisfied
Building: ahk_x11
Error target ahk_x11 failed to compile:
Showing last frame. Use --error-trace for full trace.

In src/cmd/x11/window/win-util.cr:18:54

 18 | win = XDo::Window.new(thread.runner.display.x_do.xdo_p, wid)
                                                       ^----
Error: private method 'xdo_p' called for XDo

With error trace i get even mor output....

shards build -Dpreview_mt --error-trace

Dependencies are satisfied
Building: ahk_x11
Error target ahk_x11 failed to compile:
In src/ahk_x11.cr:88:9

 88 | runner.run
             ^--
Error: instantiating 'Run::Runner#run()'

In src/run/runner.cr:88:30

 88 | spawn same_thread: true { clock }
                                ^----
Error: instantiating 'clock()'

In src/run/runner.cr:119:4

 119 | loop do
       ^---
Error: instantiating 'loop()'

In src/run/runner.cr:119:4

 119 | loop do
       ^---
Error: instantiating 'loop()'

In src/run/runner.cr:133:30

 133 | when exit_code = thread.next.receive?
                               ^---
Error: instantiating 'Run::Thread#next()'

In src/run/thread.cr:95:14

 95 | result = do_next
               ^------
Error: instantiating 'do_next()'

In src/run/thread.cr:132:18

 132 | result = cmd.run(self, parsed_args)
                    ^--
Error: instantiating 'Cmd::Base+#run(Run::Thread, Array(String))'

In src/cmd/x11/window/win-set.cr:10:8

 10 | Util.match(thread, args[2..], empty_is_last_found: true, a_is_active: true) do |win|
           ^----
Error: instantiating 'Cmd::X11::Window::Util.class#match(Run::Thread, Array(String))'

In src/cmd/x11/window/win-util.cr:18:54

 18 | win = XDo::Window.new(thread.runner.display.x_do.xdo_p, wid)
                                                       ^----
Error: private method 'xdo_p' called for XDo

Any suggestions?

**Comment by phil294** [comment]
Hello,

first of all, do you really mean to compile ahk_x11 from source (Crystal)? You do not need to follow these steps as an AutoHotkey developer, instead you can just download the binary and start scripting. This is a very common misconception which has confused so many users already somehow.

If you *did* mean to do that, however: Oops, indeed, that compilation error is on me. In file `lib/x_do/src/x_do.cr`, please make `@xdo_p` public, by changing line 19 (?) to `getter xdo_p : LibXDo::XDo*`. Then it should compile. I'll try to fix this soon so the manual intervention isn't necessary.

**Comment by phil294** [comment]
updated build instructions accordingly for building from source. It still requires some workarounds but they are not documented.

also I moved the build-from-source instructions into a separate file so hopefully ppl won't keep trying to do that when they should just download the binary instead.

thanks for the report.
