### ISSUE TITLE
how to define a hotkey with CapsLock + some other key?

### ISSUE THREAD

**Issue by jmlucjav** [phil294/AHK_X11#35]
Hi,

trying to port my scripts from win10 to ubuntu...is it possible to use Capslock with another key:

```
CapsLock & AppsKey::Send,{AppsKey}
CapsLock & .::AltTab
```

It always fails with all the variants I have tried, thanks!

**Comment by phil294** [comment]
Hi!

neither the `&` operator nor caps lock key are currently supported, sorry. Regarding the `&`, you'll have to hack something together with `GetKeyState`, and regarding the latter, I have no idea why it isn't implemented yet, maybe it will be an easy fix, if so, then soon.

**Comment by jmlucjav** [comment]
thanks Phil! Appreciated

**Comment by phil294** [comment]
CapsLock now works. As a hotkey, I have found it to work reasonably well, but with sending, not so much, because it can activate it, but not deactivate... and `&` key combinations remain tbd

**Comment by jmlucjav** [comment]
Thanks!
