### ISSUE TITLE
Issues opening GTK application

### ISSUE THREAD

**Issue by picklepissjar** [phil294/AHK_X11#37]
Arch - KDE Plasma 5.27.2
AHK_X11 Version 0.5.0 <br>
Problem: Failure to open "gnome-genius" <br>
Attempts to fix:
Tried to manually add breeze-dark/status/64/image-missing.svg to /tmp/.mount_ahk---/usr/share/icons , but couldn't get permissions working.

Demonstration:
![gnomegenius](https://user-images.githubusercontent.com/118209356/223150560-56b5c576-7336-4a3a-ae30-0946c4550b78.gif)
Error when ran in konsole:
```
Gtk-Message: 11:39:25.969: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:39:26.003: Failed to load module "colorreload-gtk-module"
Gtk-Message: 11:39:26.003: Failed to load module "window-decorations-gtk-module"

(gnome-genius:104660): Gtk-WARNING **: 11:39:26.053: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share
/icons/breeze-dark/status/64/image-missing.svg: Unable to load image-loading module: libpixbufloader-svg.so: libpixbufloader-
svg.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load 
/usr/share/icons/breeze-dark/status/64/image-missing.svg: Unable to load image-loading module: libpixbufloader-svg.so: 
libpixbufloader-svg.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)


Warning: Program 'gnome-genius' crashed.
```

**Comment by phil294** [comment]
thanks for the detailed report. Most likely related to AppImage [linuxdeploy-plugin-gtk](https://github.com/linuxdeploy/linuxdeploy-plugin-gtk/blob/master/linuxdeploy-plugin-gtk.sh). That script does some black magic and probably sets some environment variables that spawned sub gtk processes don't expect.

Can you verify it works with `NumpadEnd::Run, env -i konsole -e "gnome-genius"`?

Also, what is `/tmp/.mount_ahk`? I don't see it in the log output and I don't think ahk_x11 creates it

**Comment by phil294** [comment]
oh nevermind, the mount_ahk thing is created by AppImage

**Comment by phil294** [comment]
f

**Comment by picklepissjar** [comment]
Thanks, this solution worked for me! :D
I'll leave closing up to you.

**Comment by phil294** [comment]
Hi @picklepissjar, I think I have resolved this now. As I don't have a way to reproduce and verify this bug right now, could you kindly test if this is fixed with the most recent release version 0.5.1? https://github.com/phil294/AHK_X11/releases/tag/0.5.1 (without the `sudo` workaround thing). Then I can mark the release as ready

**Comment by picklepissjar** [comment]
Tested in 0.5.1 and it is working without the sudo workaround. :)

**Comment by phil294** [comment]
great, thanks
