### ISSUE TITLE
Stablity issue

### ISSUE THREAD

**Issue by oversky** [phil294/AHK_X11#44]
I got some stability issue with a simple script with only lines:

```
WheelUp::Send, {PGUP} 
WheelDown::Send, {PGDN}
```

The script's function is to make mouse scroll by page.
It works as I expected. 
However, it either kills the process itself or has not response to scroll within one hour or so.
My OS is MX Linux 21.3_AHS. 

I don't have much experience on reporting bugs.
Please let me know if any other information is requried.
Thank you for developing this program.

**Comment by phil294** [comment]
It never kills the process immediately though, does it? Only ever after ~1 hour?

Can you run it from a terminal and see if it prints out anything unusual at the end when it crashes? ...apart from the usual warnings and infos and errors by Gtk/Glib etc.

I guess you're using the latest version 0.5.1?

**Comment by oversky** [comment]
The script starts well at least for couple minutes.
Sometimes it keeps longer, sometimes in 10 minutes.
I am not sure what might trigger this.
And yes, the latest 0.5.1 appimage version.
I will test it in the terminal later when I am back to my machine.

**Comment by oversky** [comment]
AppImage Launcher play a trick on my MX Linux 21.3AHS.
The following run on MX Linux 21.3.

I got two different error message when the process kill itself.
$ ~/.local/bin/ahk_x11.AppImage wheelpage.ahk
Gtk-Message: 20:05:53.533: Failed to load module "canberra-gtk-module"
Interactive AHK_X11 console (REPL). Type any command. Multi-line text not supported. Press {CTRL}+C to exit.
ahk_x11> Gdk-Message: 20:06:30.420: AppRun.wrapped: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.

$ ~/.local/bin/ahk_x11.AppImage wheelpage.ahk
Gtk-Message: 20:08:34.220: Failed to load module "canberra-gtk-module"
Interactive AHK_X11 console (REPL). Type any command. Multi-line text not supported. Press {CTRL}+C to exit.
ahk_x11> double free or corruption (!prev)
Aborted

When the scroll has no response, no error message report.
$ ~/.local/bin/ahk_x11.AppImage wheelpage.ahk
Gtk-Message: 20:09:45.602: Failed to load module "canberra-gtk-module"
Interactive AHK_X11 console (REPL). Type any command. Multi-line text not supported. Press {CTRL}+C to exit.
ahk_x11>

**Comment by phil294** [comment]
oh no

**Comment by oversky** [comment]
Did I post something wrong or misunderstand your message?

**Comment by phil294** [comment]
sorry 😄 you're good, these error messages are just pretty daunting. I have no idea what the cause may be. I assume that with version 0.4.1 or 0.4.1-no-gc the bugs would not appear, so if you need this stuff soon, I suggest you try out older versions. But you don't have to, as I need to figure out the exact cause of those errors myself as I cannot reproduce them on my system.

Thanks for the detailed reports so far. I will have to replicate your system with a VM myself to test around.

**Comment by oversky** [comment]
MX Linux is just my attempt to migrate from Windows 7. 
And I feel at home when I found out this great project.
So just take your time and has no pressure on it.
What system do you use?

MX Linux does not use systemd.
I know this can have some compatibility issues.
Do this matter?
https://mxlinux.org/wiki/system/systemd/

**Comment by phil294** [comment]
ah, interesting... yes I guess it could matter, essentially *anything* could matter, but the existence of AppImage wrapper *should* free us from most headaches.

I'm using Manjaro Linux Linux 5.4 XFCE. I presume it's something about MX Linux because I have never gotten a similar error report before and several people are using it successfully, e.g. on Ubuntu.

**Comment by oversky** [comment]
Thank you for addressing this issue.
I am more than happy to see the version 1.0 coming.
I will test AHK_X11 when I sort out my computer hardware problem.
Best,



Philip Waritschlager ***@***.***> 於 2023年7月20日 週四 下午8:57寫道：

**Comment by oversky** [comment]
After 4 hours of usage, no stablity issue occurs.
This is much better than v0.4.1 and v0.5.1.
Good job. 

I have to mention that the mouse tested is G603 instead of G602 in the previous tests.
G602 just died days before before v1.0.
Therefore, I can't have the test in exactly the same conditions.

I found one bug not related to stability issue.
I will file it in a new ticket.
Thank  you again.
