### ISSUE TITLE
'XButton2' key mapping not working.

### ISSUE THREAD

**Issue by Shringe** [phil294/AHK_X11#48]
I can't rebind XButton2(mouse 5) using 'XButton2::', it just doesn't get picked up. XButton1(mouse 4) works just fine though. 

Here is the script:
`Script.ahk`:
```ahk
; doesn't get picked up
XButton2::
    Send, mouse5
Return

; works just fine
XButton1::
    Send, mouse4
Return
```

I'm rusty with AHK, so sorry if its just a syntax error.

**Comment by phil294** [comment]
thanks for reporting this. should be fixed now.
