### ISSUE TITLE
both hotkey and function use mouse button, not working

### ISSUE THREAD

**Issue by wangsitan** [phil294/AHK_X11#49]
These works fine:
```
a::MouseClick, RIGHT

MButton::Send, xxx
```

But this doesn't work for me:
```
MButton::MouseClick, RIGHT
```
When I load this script, clicking mouse middle button did nothing (no middle button function, nor right button function).

I didn't define the hotkey MButton twice at the same time. Only one ahk script is loaded at one time.

* env: manjaro-22.1.3-x86_64, KDE, X11
* mouse: SANWA wired USB mouse

**Comment by phil294** [comment]
it looks like you are right. However, this seems to be a limitation of X11, perhaps of Linux in general. I had actually faced this too several  years ago, at that time with `xbindkeys`+`xte` (same with `xdotool`).

The only solution in your case is to replace `MButton::` with `MButton up::`. Hope that's still satisfying to you. I will also put this in the Readme.

thanks for the report!
