### ISSUE TITLE
RAlt remapping problem.

### ISSUE THREAD

**Issue by oversky** [phil294/AHK_X11#50]
AHK version tested: v1.0
OS: MX Linux 21.3 AHS
Firefox: v108.0.2

script:
RAlt::Send, ^{Space}

Problem:
I use the above script to switch the input method quickly with RAlt.
However, in Firefox, the hidden Menu bar will temporary show up when RAlt is pressed.
AHK not only send ^{Space} (the input method does switched as expected), 
but also send RAlt to the active window.
In the words, AHK does not block the default key function as expected.
This also happens in v0.4.1, but not in v0.5.1.

https://support.mozilla.org/en-US/kb/restore-menu-bar-firefox

**Comment by phil294** [comment]
Hi @oversky, I think this is fixed now, please try version 1.0.1!

**Comment by oversky** [comment]
Yes, now it works. 
Thank you for fixing this so quickly.
