### ISSUE TITLE
Numpad number keys and dot do not work as hotkeys (Numlock on)

### ISSUE THREAD

**Issue by davidhfo** [phil294/AHK_X11#52]
Using `Numpad0`…`Numpad9` as hotkey:
Seems to trigger hotkey, but there is no output visible.

`NumpadDot`:
Does not trigger hotkey. A period appears on the screen.

Using the same buttons to trigger hotkeys but with Numlock _off_ setting work fine (`NumpadIns`, `NumpadEnd`, `NumpadDel`, etc.).

The following Numpad keys are unaffected:
`NumpadDiv` - the slash key
`NumpadMult` - the asterisk key
`NumpadAdd` - the plus key
`NumpadSub` - the minus key
`NumpadEnter` - the Enter key

Solus 4.4, Plasma edition

**Comment by phil294** [comment]
thanks for the  report! should work now with v1.0.2, except NumpadDot always prints a dot for me for some reason so it can't be "grabbed" properly. Not quite sure why
