### ISSUE TITLE
Performance: AHK_X11 vs RobotJS?

### ISSUE THREAD

**Issue by moshpirit** [phil294/AHK_X11#55]
Hi, I just wanted to know about the performance, how light is it in comparison with other software like RobotJS? I'm an ignorant of both software, I just wanted to know before committing to learn and use any of them.

**Comment by phil294** [comment]
I have no idea about RobotJS so I can't compare anything here. ahk_x11 contains relatively little overhead though. Please have a look at the Performance section in the Readme, it really includes all the information I have.
