### ISSUE TITLE
Is it possible to prevent taskbar popping up when pressing hotkey in fullscreen game?

### ISSUE THREAD

**Issue by Shringe** [phil294/AHK_X11#59]
I have a AHK script to bind my mouse sidebuttons to keys for a game, and whenever they are pressed the taskbar pops up over the game, until I re-fullscreen the game. Im not sure if this is a bug, or limitation with KWin(also happens with compositor off), this project, or X11. Does anyone know what causes this, and if there is a fix?

**Comment by phil294** [comment]
hi! what distribution are you using exactly?

what do you mean by taskbar - the application launcher only, or the entire bar? And once the bar receives focus, shouldn't that even cancel the fullscreen of the game?

Also, does this happen with all hotkeys or just certain ones?

Anyway, please try adding `#XGrabRoot` anywhere in your script, perhaps this fixes it.

**Comment by Shringe** [comment]
By taskbar I mean the entire 'panel' in Plasma. It for some reason does not minimize the game, most likely was in windowed borderless not fullscreen I assume. The hotkeys that were tested were XButton1, XButton2, and MButton. `#XGrabRoot` for some reason fixes it, although it does not ask for password or root permission in any way.

**Comment by phil294** [comment]
Ok. The root `xgrabroot` doesn't refer to root user but x11 "root window", so this is expected. I haven't quite figured out why this directive is necessary though. What Linux distribution/version are you using exactly?

**Comment by phil294** [comment]
ok arch + KDE, so probably the problem of #51 applies to all KDE installations, not just Solus Linux. In my tests, that wasn't the case though. Needs more investigation. For you it should not matter, just keep using the directive.
