### ISSUE TITLE
Came here just to say thank you

### ISSUE THREAD

**Issue by Whyglobaleyes** [phil294/AHK_X11#63]
Hello, 

Apologies in advance - this isn't an issue but I'm hoping for the best chance that this reaches @phil294 and any other contributors, mods or helpful folks. I can't believe I've never found ahk_x11 before.

**Thank You**

I've used AHK on windows for many years - since it was first written. Jumped to Linux for all the machines I control about 8 years ago and since then the only thing I've really missed has been the ease of scripting user input with AHK. I've sunk a monumental amount of time cobbling together xdotool, sendkey and sendmouse and I can do it if I really have to but it's all so clumsy and takes me too long to be worthwhile. 

ahk_x11 however is a familiar delight! Within moments of installing I had a 2 minute script that saved me an hour of manually repeating keystrokes! It's fabulous, thank you very much. Keep up the good work! I'll try to buy you a coffee or something and I hope you enjoy the warm glow of satisfaction at a job well done, of a proper contribution to well-being in the world.

bw
ygi

**Comment by phil294** [comment]
Hi! aww, thanks for the kind words! 😊 and you're certainly very welcome.
it's great to know this experiment turned out to be helpful to you (and also others - it did blow up quite a bit, after all).
