### ISSUE TITLE
Gonna need some help here

### ISSUE THREAD

**Issue by DarkblooM-SR** [phil294/AHK_X11#66]
Okay, so I'm trying to make a script that spams a key when said key is pressed, here's my code so far:
```
#SingleInstance force

*Space:: {
  GetKeyState, state, Space
  Loop {
    if state = D
      Send, {SPACE}
      Sleep 5
  }
}
```
And here's the compiler output:
```
Unexpected '}' in line 9.  (Build::SyntaxException)
  from /tmp/.mount_auto_bi4yqSl/AppRun.wrapped in '??'
  from /tmp/.mount_auto_bi4yqSl/AppRun.wrapped in '??'
  from /tmp/.mount_auto_bi4yqSl/AppRun.wrapped in '__crystal_main'
  from /tmp/.mount_auto_bi4yqSl/AppRun.wrapped in 'main'
  from /lib/x86_64-linux-gnu/libc.so.6 in '??'
  from /lib/x86_64-linux-gnu/libc.so.6 in '__libc_start_main'
  from /tmp/.mount_auto_bi4yqSl/AppRun.wrapped in '_start'
  from ???
```
Not sure what I'm missing, enlightenment would be appreciated.

**Comment by phil294** [comment]
Since we're strictly at ancient v1.0-syntax, hotkey bodies must not be enclosed by `{}` but by routine-like code:

```ahk
*Space::
; ... your commands
Return
```
With that said, sending a key *while the same key is physically pressed down by you* is a use case that seems to be impossible right now. So the trigger hotkey needs to be something else than the key you want to send.

There's more info to be found here in the last two comments: https://github.com/phil294/AHK_X11/issues/26#issuecomment-1358157028

**Comment by DarkblooM-SR** [comment]
Do I need to remove brackets from the loop as well? I'm still getting the same error.

**Comment by phil294** [comment]
huh it seems you also have to change
```ahk
loop {
```
to
```ahk
loop
{
```
.
Could have sworn this once worked.

I then tried your code snippet myself and it seems to behave pretty randomly. You'll have to tweak things around until things work like you want them to. Feel free to share your final soltion :-)

**Comment by DarkblooM-SR** [comment]
That helped, but it seems like the if statement is ignored completely, the `Send` is constantly firing

**Comment by phil294** [comment]
there's a mistake in your code I just noticed. You need to move the `GetKeyState` **into** the loop or otherwise it's only checked once at the start

But then again, because of the bug I mentioned, it probably never works great. Try using another hotkey instead.

```ahk
F1::
  Loop
  {
    GetKeyState, state, F1
    if state = D
      Send, {SPACE}
      Sleep 5
  }
```

**Comment by DarkblooM-SR** [comment]
Ah yes that makes sense lmao
And yeah I changed the sent key, thanks
