### ISSUE TITLE
Hotstring

### ISSUE THREAD

**Issue by devincurrie** [phil294/AHK_X11#69]
Hello,

Thank you for creating AHK_X11 to work on Linux.

I primarily use Windows AHK's hotstring feature to quickly shorthand text. For example:

:o:demail::devin@example.com

Using AHK_X11, the above code would automatically type out the text replacing the @ symbol with a number 2 as follow :

devin2example.com

According to AHK_X11 documentation at https://phil294.github.io/AHK_X11/#Hotstrings.htm

Do I need to add an escape character in front of the @ symbol in order to type it out? Adding an escape tilde symbol ` in front of the @ symbol didn't help.

https://phil294.github.io/AHK_X11/#h_EscapeChar.htm

Thanks,

Devin

**Comment by phil294** [comment]
Hi!   This is a bug related to `Send`: #32 
so you  either need to write `+@` or use the `r` option (send raw)

**Comment by devincurrie** [comment]
Hi Phil,

> Hi! This is a bug related to `Send`: #32 so you either need to write `+@` or use the `r` option (send raw) for now

Sorry for the late reply. I have successfully tested your suggestion using the '+@" combination.

Please provide me with an example using the send raw option if I'd like to auto replace "demail" to "devin@example.com" ? 

Thanks!

Devin

**Comment by phil294** [comment]
good to hear.

sendraw:

`:R:demail::devin@example.com`

the usage of options, including the `R` option, is documented in the Hotstrings documentation link that you posted in your first post
