### ISSUE TITLE
Running a script with a defined hotkey(s) fires the first one on start

### ISSUE THREAD

**Issue by Drugoy** [phil294/AHK_X11#7]
Running a 1-liner script ```x::msgbox hi``` it to show the message box with text `hi` right on start.
The same happens if the script is re-written into these 3 lines:
```
x::
    msgbox hi
return
```
If multiple hotkeys are declared - it fires only the first one.
Putting something (like a `SingleInstance Force`) above declared hotkey doesn't change the behavior.

**Comment by phil294** [comment]
thanks, good poinnt. in the meantime, you can solve that by adding a `return` on top, which stops the auto execute section.
