### ISSUE TITLE
Not firing

### ISSUE THREAD

**Issue by zefrs** [phil294/AHK_X11#72]
- System = Debian 12

I was using the below script perfectly on a previous installation of Debian, however i have reinstalled and it does not seem to be working any longer.  Are there any issue with my script?

```
*DEL:: Suspend, Toggle
*~$2::
IfWinActive, wow.exe
Sleep 100
Loop
{
    GetKeyState, 2State, 2, P
    If 2State = U
        break  
    Sleep 50
    Send, {f2}
}
Return

*~$3::
IfWinActive, wow.exe
Sleep 100
Loop
{
    GetKeyState, 3State, 3, P
    If 3State = U
        break  
    Sleep 50
    Send, {f3}
}
Return
```

**Comment by phil294** [comment]
Looks fine to me 🤷

how did you install it? Download the AppImage file, run it and click the "Install" button?

Can you please provide more details what exactly doesn't work? Perhaps try putting some basic `MsgBox`es in various places of your script, or even run your script via command line: This may show additional errors. `path/to/ahk_x11.AppImage path/to/script.ahk`

**Comment by phil294** [comment]
However, are you sure the `IfWinActive, wow.exe` does what you think it does? This only applies to the `Sleep 100` below so it seems rather unnecessary.

**Comment by zefrs** [comment]
Hi @phil294 - so i would only like the macro to fire when the wow.exe window is active.
below is the output when running from the terminal:

`'/home/xxx/AHK/ahk_x11.AppImage' '/home/xxx/AHK/2.ahk' 

(process:7066): Gtk-WARNING **: 08:19:08.860: Locale not supported by C library.
	Using the fallback 'C' locale.
Interactive AHK_X11 console (REPL). Type any command. Multi-line text not supported. Press {CTRL}+C to exit.
ahk_x11> 2^[OQ^[OQ^[OQ^[OQ^[OQ^[OQ^[OQ^[OQ^[OQ^[OQ^[OQ^[OQ^[OQ^[OQ^[OQ^[OQ
`

**Comment by zefrs** [comment]
Update:

I get this working, you were correct the window was named incorrectly and i removed the Sleep 100.
