### ISSUE TITLE
libssl.so.1.1 missing

### ISSUE THREAD

**Issue by Pineappleman123** [phil294/AHK_X11#9]
Tried to run on Pop OS 22.04 but got an error saying: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by phil294** [comment]
[Are you using Wayland](https://unix.stackexchange.com/a/355476/103120)? If so, it's not yet supported, sorry.

**Comment by DashKiller** [comment]
Would be nice if wayland support could come soon!
