### ISSUE TITLE
Hotkey Alt+Ctrl+Shift+letter doesn't work

### ISSUE THREAD

**Issue by brackleian** [phil294/AHK_X11#94]
Trying to set up hotkey with, e.g., Alt+Ctrl+Shift+P, which I want to send my phone number. My .ahk file has:
`+!^P::`
`Sleep, 100`
`SendRaw, +64 12 345 6789`
`return`
Other hotkeys work, without the Shift qualifier, but the one shown just does nothing.
I'm running Xubuntu 24.04.

**Comment by phil294** [comment]
I can't say much here except it works perfectly on my machine

**Comment by brackleian** [comment]
Hmm...weird. Tried running `xev`, without AHK running, and it shows events for each of the Alt, Ctrl, Shift keys as I press them, but no event at all for any key press after that, until I release one of the modifiers. So, maybe something is filtering out keyboard events before they even get to X, or perhaps my keyboard is duff? I'll see if I can find another one to try.

**Comment by brackleian** [comment]
Hmm...weird. Tried running `xev`, without AHK running, and it shows events for each of the Alt, Ctrl, Shift keys as I press them, but no event at all for any key press after that, until I release one of the modifiers. So, maybe something is filtering out keyboard events before they even get to X, or perhaps my keyboard is duff? I'll see if I can find another one to try.

**Comment by brackleian** [comment]
Yep, switching keyboards fixed it. Sorry for wasting your time...
